### ISSUE TITLE
Chore: sneak in all the changes that don't need new releases

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1190]
There are many trivial updates that need to be done to many components that don't warrant npm releases:

- [x] Update JS to comply with new linting
- [x] Reorganize and tidy readmes #1189 
- [x] Update some component classifications #1188 
- [x] Tidy changelogs (bullets: no `-`, use `*`) #1191
 
Might be others as well.

Process:

- [x] ship any components to npm that need to go there
- [x] tag a release as usual
- [x] sneak in the above commits
- [x] tag a release (without doing `lerna publish`)
- [ ] victory lap

We should try to wrap this up today or by tomorrow morning so we don't have to postpone any work that needs to go on npm.

**Comment by khawkins98** [comment]
My sorcery seems to have worked.

Made this 2.3.1-alpha.1 https://github.com/visual-framework/vf-core/releases/tag/v2.3.1-alpha.1

And: 

```bash
mac:vf-component-library khawkins$ lerna changed
lerna notice cli v3.10.7
lerna info versioning independent
lerna notice Current HEAD is already released, skipping change detection.
lerna info No changed packages found
mac:vf-component-library khawkins$ 
```
