### ISSUE TITLE
Roadmap for v2.0.0-alpha.3

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#160]
# 🎆 Released! 🎆

See https://github.com/visual-framework/vf-core/releases/tag/v2.0.0-alpha.3

# Release to-do script

1. [x] Finish up outstanding ticket/tasks 
1. [x] Do release notes
1. [x] Push to npm (lerna)
   - `lerna publish --no-git-tag-version  --conventional-commits --no-push`
       - if you mess up, and need to run again without pushing to npm `--skip-npm`
    - verify no tags added: `git tag`
    - PR version changes
1. [x] Sync changes to `vf-child-template`, `npm update` it
1. [x] Merge to `master`
1. [x] Tag release on `master`
