### ISSUE TITLE
Focus indicator (outline) of link on vf-banner is hard to spot

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1782]
When a link is selected with the keyboard on vf-banner, the white focus indicator (outline) is hard to spot:

![outline-link-banner-Screenshot 2022-07-01 at 12 49 04](https://user-images.githubusercontent.com/20280139/176890700-fd14b0b5-8a2f-4a8f-bd7a-66508cb4a32d.png)

This is confirmed by the contrast checker - the almost 1:1 ratio between the white outline and the light yellow background (#FFFADC) fails all contrast checks including the one for "Graphical Objects and User Interface Components":

https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=FFFADC

The required ratio for these elements is at least 3:1.

If we turn the outline from white to the same black as the text on the banner (#373A36) or the same blue as a link (#3B6FB6) we will pass this test:

Black: https://webaim.org/resources/contrastchecker/?fcolor=373A36&bcolor=FFFADC

Blue: https://webaim.org/resources/contrastchecker/?fcolor=3B6FB6&bcolor=FFFADC

Note that these tests also confirm that the contrast between the black text (#373A36) or the blue link (#3B6FB6) and the light yellow background (#FFFADC) is sufficient.

The blue outline will be more appropriate for the banner that we use on the EMBL-EBI corporate page for feedback where the link is blue too:
![outline-send-feedback-banner-Screenshot 2022-07-01 at 11 44 50](https://user-images.githubusercontent.com/20280139/176893872-238915d1-1d7b-4d5a-b8ad-2b0967ea2750.png)

However, we need to make sure that new outline colour works with the other background colours of the banner (orange, red or green).

Also see related issue https://github.com/visual-framework/vf-core/issues/1758

**Comment by nikiforosk** [comment]
@nikiforosk to test the contrast between outline and background for other variants.

@pacope92 to prototype some alternatives to the outline when the contrast fails.

**Comment by nikiforosk** [comment]
@pacope92 I checked the contrast of the focus indicator with the four background colours of [vf-banner](https://stable.visual-framework.dev/components/vf-banner/index.html). I suggest the following:

- [x] Use black (#373A36) outline for yellow, orange and green background (the current white one fails the required 3:1 contrast: see tests below).
- [x] Use black outline for [top variant](https://stable.visual-framework.dev/components/vf-banner/index.html#vf-banner--top) (which also has an orange background).
- [x] Keep the white outline for the red background (changing this to black will fail the contrast check).
- [x] Remove blue outline from [fixed variant](https://stable.visual-framework.dev/components/vf-banner/index.html#vf-banner--fixed) (just keep the white one).

-- Contrast checks ---

We want to achieve a contrast ratio of at least 3:1

**White outline** (current implementation):

- [ ] [White on yellow](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=FFFADC) (#FFFADC): 1.05:1 FAIL
- [ ] [White on orange](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=F49E17) (#F49E17): 2.15:1 FAIL
- [ ] [White on green](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=6CC24A) (#6CC24A): 2.22:1 FAIL
- [x] [White on red](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=D41645) (#D41645): 5.24:1 PASS

**Black outline** (#373A36):

- [x] [Black on yellow](https://webaim.org/resources/contrastchecker/?fcolor=373A36&bcolor=FFFADC): 10.96:1 PASS
- [x] [Black on orange](https://webaim.org/resources/contrastchecker/?fcolor=373A36&bcolor=F49E17): 5.35:1 PASS
- [x] [Black on green](https://webaim.org/resources/contrastchecker/?fcolor=373A36&bcolor=6CC24A): 5.19:1 PASS
- [ ] [Black on red](https://webaim.org/resources/contrastchecker/?fcolor=373A36&bcolor=D41645): 2.19:1 FAIL

**Blue outline** (#005FCC: this is the default colour of the outline for links and other interactive elements):

- [ ] [Blue on yellow](https://webaim.org/resources/contrastchecker/?fcolor=005FCC&bcolor=FFFADC): 5.68:1 PASS
- [ ] [Blue on orange](https://webaim.org/resources/contrastchecker/?fcolor=005FCC&bcolor=F49E17): 2.77:1 FAIL
- [ ] [Blue on green](https://webaim.org/resources/contrastchecker/?fcolor=005FCC&bcolor=6CC24A): 2.69:1 FAIL
- [ ] [Blue on red](https://webaim.org/resources/contrastchecker/?fcolor=005FCC&bcolor=D41645): 1.14:1 FAIL
- [ ] [Blue on gray](https://webaim.org/resources/contrastchecker/?fcolor=005FCC&bcolor=707372) (#707372 this is the background colour of the fixed variant): 1.24:1 FAIL

[The colours](https://stable.visual-framework.dev/design-tokens/theming/) that are currently used for the backgrounds are:

- UI Yellow (#fffadc)
- EMBL Orange (#f49e17)
- EMBL Red (#d41645)
- EMBL Green, Light Tint (#6cc24a)
- (Gray) Neutral 600 (#707372)

We also tested UI Red (#d32f2f) as an alternative to EMBL Red (#d41645) but this also [fails the contrast test with the black outline](https://webaim.org/resources/contrastchecker/?fcolor=373A36&bcolor=D32F2F).

**Comment by nikiforosk** [comment]
@pacope92 I can preview the changes on the variants that have links and they are as expected:
https://latest.visual-framework.dev/components/vf-banner/index.html

Can you please add a hyperlink to the Warning (orange) and Danger (red) variant when you have the chance?

**Comment by nikiforosk** [comment]
Thanks @pacope92 I can see all changes in latest now:
https://stable.visual-framework.dev/components/vf-banner/index.html

**Comment by nikiforosk** [comment]
The changes have now been released: https://stable.visual-framework.dev/components/vf-banner/
