### ISSUE TITLE
VF Breadrumb update as per Intranet implementation

### ISSUE THREAD

**Issue by bhushan-ebi** [visual-framework/vf-core#1976]
VF Breadcrumb component needs to be reviewed and changes need to be made as per the recent implementation in Intranet
Possible changes :

- Remove restriction of 3 links
- Styling changes
- Responsive changes (Open seperate ticket if needed)

**Edit** ---------------------------------------------------------------------------------(**Follow up tasks added**)

Sequel to the discussion we had on Monday 15h April, Follow up tasks have been added for the breadcrumb updates

- [x] #2009
- [x] #2008
- [x] #2010

**Comment by Adedoyinebi** [comment]
**Useful links**:

- [Slides on the breadcrumb's functionality and best practices](https://docs.google.com/presentation/d/1ZsYfYUnkRtGG_-15Awfck65g5voC2meSVvA_qoecn5U/edit?usp=sharing)
- [Intranet design of the breadcrumbs in figma ](https://www.figma.com/file/LIIgoNnuREnUcNf2WCU6ZF/Intranet?type=design&node-id=2080%3A26756&mode=design&t=CqJ9iIWhPm3TWGqP-1)

**Task**
- Review changes that should be added in the[ vf-breadcrumb](https://stable.visual-framework.dev/components/vf-breadcrumbs/) component
- Recommend updates
- Update the vf-breadcrumb in [figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A137&mode=design&t=VA2DqXzUFCxNy1Bn-1) and [html](https://stable.visual-framework.dev/components/vf-breadcrumbs/)
- Update documentation if needed
- Check for accessibility and responsiveness

**Comment by Adedoyinebi** [comment]
From the review of the breadcrumbs design during the Intranet project. The following changes should be made to improve the Vf-breadcrumbs

**Component changes**:

- Improve the target area for the breadcrumb
    - Increase the spacing after the “>” symbol from 4px to 8px to avoid [overlap of touch target areas](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum#target-spacing-toolbar) for small words in the breadcrumb
    - On mobile where a larger touch are is required 8px padding should be added above and below the breadcrumb to achieve a height of 44px which is [recommended for mobile devices](https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced#benefits).
- Shorten breadcrumb trail on mobile to show only the parent page in the site architecture ([Design of the breadcrumb trail showing the previous page](https://www.figma.com/file/LIIgoNnuREnUcNf2WCU6ZF/Intranet?type=design&node-id=2080%3A27040&mode=design&t=lhop5tY3QkWQ6lAy-1))

**Documentation updates** 

- Guidelines should be updated to showing the full navigation path on desktop ✔(This has been done)
- Usage guidelines for the responsive variant should be added

**Design links for reference - Intranet project**

- [Breadcrumb for desktop](https://www.figma.com/file/LIIgoNnuREnUcNf2WCU6ZF/Intranet?type=design&node-id=2080%3A26758&mode=design&t=lhop5tY3QkWQ6lAy-1)
- [Mobile responsive breadcrumb design](https://www.figma.com/file/LIIgoNnuREnUcNf2WCU6ZF/Intranet?type=design&node-id=2080%3A27040&mode=design&t=lhop5tY3QkWQ6lAy-1)

**Next steps**

- Update design of the vf-breadcrumbs in [figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A137&mode=design&t=EUgg8l8nCDHovrx6-1) and on the [vf-site](https://stable.visual-framework.dev/components/vf-breadcrumbs/)
- Develop responsive version of vf-breadcrumbs
- Add documentation for mobile responsiveness

**Comment by Adedoyinebi** [comment]
Sequel to the discussion we had on Monday 15h April, Follow up tasks have been added for the breadcrumb updates

- [ ]  Update design of the vf-breadcrumbs in figma and on the vf-site
- [ ]  Develop responsive vf-breadcrumbs
- [ ]  Add documentation for responsive vf-breadcrumb

**Comment by bhushan-ebi** [comment]
- [ ] Test
- [ ] Test

**Comment by Adedoyinebi** [comment]
Test

- [ ] test task
- [ ] test task

**Comment by bhushan-ebi** [comment]
PR - https://github.com/visual-framework/vf-core/pull/2044
