### ISSUE TITLE
Revising our npm publishing script

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#583]
vf-core is home to many VF components. It is [a monorepo](https://gomonorepo.org) and we publish using [Lerna](https://github.com/lerna/lerna#about), and there's room for improvement.

## The two issues

1. We've limited component publishing to npm only when we also are ready for vf-core releases
2. We've not been using Lerna's git tags due to the volume it creates (#tagSpam), however this also means lerna thinks every package has changed every time, resulting in needless version bumps

What we need to do is add a [named tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) for Lerna to use in its `git diff`, this will allow us to publish our components adhoc without superfluous git tags and without waiting for the next vf-core release. 

## Proposed revised tagging setup

- For `vf-core: carry on with our tagged releases made in the GitHub UI
- For components we:
   - (Have gone back and added a named tag for the last beta release: https://github.com/visual-framework/vf-core/releases/tag/components.20190916-01)
   - Add tags for component releases whenever needed (independent of vf-core releases) with this  naming convention:  
      - `components.20190916-01`
      - `components.YYYYMMDD-##`

## Component release workflow

1. See a list of changed packages: 
    - `lerna changed`
2. If you want to test publish 
      - `lerna publish --no-git-tag-version  --conventional-commits --no-push --skip-npm prerelease `
      - Afterward, reset your branch `git reset --hard`
3. Then publish to npm
      - `lerna publish --no-git-tag-version  --conventional-commits --no-push prerelease`
      - You'll probably have lost your local git changes, so: reset your branch `git reset --hard`
      - `lerna publish --no-git-tag-version  --conventional-commits --no-push --skip-npm prerelease`
      - verify no tags added: `git tag`
4. push your changes to develop with commit message in a format of: `Component release 20190930-01`
5. add a tag `git tag -a components.YYYYMMDD-01 -m 'Snapshot of components for lerna'`
6. push the tag `git push origin --tags`

## Appendix of useful commands

- `lerna ls` list all packages known to lerna
- `lerna ls --since af04cb2a` list all changed packages since a commit (sadly not combinable with lerna publish)
- `lerna diff` all changes since last publish
- `lerna changed` all packages changed

## To-do-s

- [x] Verify this approach works
- [x] Add it to our documentation
    - [x] https://github.com/visual-framework/vf-welcome/blob/master/src/site/developing/guidelines/versioning.njk
    - [x] https://github.com/visual-framework/vf-core/blob/develop/README.md
- [ ] Make a blog post

**Comment by khawkins98** [comment]
As @sturobson put it on Slack: 

> ugh, you’d think this would be a solved, documented problem somewhere.

In my few hours of researching this issue, I've not seen the above approach written about. So it's probably worth a blog post.

**Comment by khawkins98** [comment]
In the name of closing this ticket, i threw together this blog post for posterity.
